---

- hosts: all
  become: true
  tasks:

  - name: update yum repository 
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "10"

  - name: install httpd package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "10"
    
  - name: add php support for apache2
    yum:
      name: php
      state: latest
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "10"

